stages:
  - download
  - build

variables:
  IMAGE_NAME: jitesoft/node-yarn

download:
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  stage: download
  variables:
    GIT_STRATEGY: none
  before_script:
    - apk add --no-cache gnupg
    - wget -qO- https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --import
  script:
    - wget -q https://yarnpkg.com/latest.tar.gz
    - wget -q https://yarnpkg.com/latest.tar.gz.asc
    - gpg --verify latest.tar.gz.asc
  artifacts:
    when: on_success
    name: yarn
    paths:
      - ./latest.tar.gz
    expire_in: 2 days

.build: &build
  image: docker:latest
  stage: build
  services:
    - docker:dind
  dependencies:
    - download
  before_script:
    - echo ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token registry.gitlab.com --password-stdin
    - echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USER} --password-stdin
  script:
    - docker build --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} --build-arg "NODE_VERSION=${VERSION}" -f slim/Dockerfile .
    - TAGS="${VERSION} ${EXTRA_TAGS}"
    - |
      for tag in ${TAGS}; do
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} ${CI_REGISTRY_IMAGE}:${tag}-slim
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} ${IMAGE_NAME}:${tag}-slim
        docker push ${CI_REGISTRY_IMAGE}:${tag}-slim
        docker push ${IMAGE_NAME}:${tag}-slim
      done
    - docker build --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} --build-arg "NODE_VERSION=${VERSION}" -f full/Dockerfile .
    - |
      for tag in ${TAGS}; do
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} ${CI_REGISTRY_IMAGE}:${tag}
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} ${IMAGE_NAME}:${tag}
        docker push ${CI_REGISTRY_IMAGE}:${tag}
        docker push ${IMAGE_NAME}:${tag}
      done

build:stable:
  <<: *build
  variables:
    VERSION: "10"
    EXTRA_TAGS: "stable current lts dubnium"

build:latest:
  <<: *build
  variables:
    VERSION: "12"
    EXTRA_TAGS: "latest"
