image: docker:latest

stages:
  - slim
  - full


.build:slim: &slim
  stage: slim
  before_script:
    - echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USER} --password-stdin
    - docker pull jitesoft/node-base:${BUILD_TYPE}-slim
  script:
    - BUILD=$(docker build --build-arg BUILD_TYPE=${BUILD_TYPE} -q -f slim/Dockerfile .)
    - NODE=$(docker inspect -f '{{range $index, $value := .Config.Env}}{{if eq (index (split $value "=") 0) "NODE_VERSION" }}{{range $i, $part := (split $value "=")}}{{if gt $i 1}}{{print "="}}{{end}}{{if gt $i 0}}{{print $part}}{{end}}{{end}}{{end}}{{end}}' ${BUILD})
    - YARN=$(docker run --rm ${BUILD} yarn -v)
    - echo "Building for node v ${NODE} and Yarn v ${YARN} The image build hash is ${BUILD}"
    - NODE_SHORT="${NODE:0:1}"
    - TAGS="${NODE}-slim ${NODE_SHORT}-slim ${EXTRA_TAGS}"
    - for tag in $TAGS; do docker tag $BUILD jitesoft/node-yarn:${tag}; docker push jitesoft/node-yarn:${tag}; done

.build:full: &full
  stage: full
  before_script:
    - echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USER} --password-stdin
    - docker pull jitesoft/node-yarn:${BUILD_TYPE}-slim
  script:
    - BUILD=$(docker build --build-arg BUILD_TYPE=${BUILD_TYPE} -q -f full/Dockerfile .)
    - NODE=$(docker inspect -f '{{range $index, $value := .Config.Env}}{{if eq (index (split $value "=") 0) "NODE_VERSION" }}{{range $i, $part := (split $value "=")}}{{if gt $i 1}}{{print "="}}{{end}}{{if gt $i 0}}{{print $part}}{{end}}{{end}}{{end}}{{end}}' ${BUILD})
    - YARN=$(docker run --rm ${BUILD} yarn -v)
    - NODE_SHORT="${NODE:0:1}"
    - TAGS="${NODE} ${NODE_SHORT} ${EXTRA_TAGS}"
    - for tag in $TAGS; do docker tag $BUILD jitesoft/node-yarn:${tag}; docker push jitesoft/node-yarn:${tag}; done


build:slim:stable:
  <<: *slim
  variables:
    BUILD_TYPE: "stable"
    EXTRA_TAGS: "stable-slim current-slim lts-slim carbon-slim current-slim"

build:slim:latest:
  <<: *slim
  variables:
    BUILD_TYPE: "latest"
    EXTRA_TAGS: "latest-slim"

build:full:stable:
  <<: *full
  variables:
    BUILD_TYPE: "stable"
    EXTRA_TAGS: "stable current lts carbon current"

build:full:latest:
  <<: *full
  variables:
    BUILD_TYPE: "latest"
    EXTRA_TAGS: "latest"