image: docker:latest

variables:
  IMG_NAME: "jitesoft/node-yarn"
  DOCKER_FILE: "/full/latest/Dockerfile"

deploy_latest:  
  variables:
    DOCKER_FILE: "/full/latest/Dockerfile"
  script:
    - BUILD=$(docker build -q -f ${DOCKER_FILE} .) # Build the image and store the hash in the BUILD var.
    - YARN=$(getenv.sh YARN_VERSION ${BUILD})      # Fetch the yarn version.
    - NODE=$(getenv.sh NODE_VERSION ${BUILD})      # Fetch the node version.
    - NODE_SHORT="${NODE:0:1}"                     # Get the short-node version (major version).
    - TAGS=( "${NODE}" "${NODE}-${YARN}" "${NODE_SHORT}" "${NODE_SHORT}-${YARN}" "latest" )
    - docker login -u $HUB_USER -p $HUB_PW         # Login to hub!
    - for tag in "${TAGS[@]}" do \                 # Iterate all tag names and push to docker hub.
        docker tag $BUILD ${IMG_NAME}:${tag} \
        docker push ${IMG_NAME}:${TAG} \
      done
  only:
    - master

deploy_stable:  
  variables:
    DOCKER_FILE: "/full/stable/Dockerfile"
  script:
    - BUILD=$(docker build -q -f ${DOCKER_FILE} .)
    - YARN=$(getenv.sh YARN_VERSION ${BUILD})
    - NODE=$(getenv.sh NODE_VERSION ${BUILD})
    - NODE_SHORT="${NODE:0:1}"
    - TAGS=( "${NODE}" "${NODE}-${YARN}" "${NODE_SHORT}" "${NODE_SHORT}-${YARN}" "stable" )
    - docker login -u $HUB_USER -p $HUB_PW
    - for tag in "${TAGS[@]}" do \
        docker tag $BUILD ${IMG_NAME}:${tag} \
        docker push ${IMG_NAME}:${TAG} \
      done
  only:
    - master

deploy_latest_slim:  
variables:
    DOCKER_FILE: "/slim/latest/Dockerfile"
  script:
    - BUILD=$(docker build -q -f ${DOCKER_FILE} .)
    - YARN=$(getenv.sh YARN_VERSION ${BUILD})
    - NODE=$(getenv.sh NODE_VERSION ${BUILD})
    - NODE_SHORT="${NODE:0:1}"
    - TAGS=( "${NODE}-slim" "${NODE}-${YARN}-slim" "${NODE_SHORT}-slim" "${NODE_SHORT}-${YARN}-slim" "latest-slim" )
    - docker login -u $HUB_USER -p $HUB_PW
    - for tag in "${TAGS[@]}" do \
        docker tag $BUILD ${IMG_NAME}:${tag} \
        docker push ${IMG_NAME}:${TAG} \
      done
  only:
    - master

deploy_stable_slim:  
  variables:
    DOCKER_FILE: "/slim/stable/Dockerfile"
  script:
    - BUILD=$(docker build -q -f ${DOCKER_FILE} .)
    - YARN=$(getenv.sh YARN_VERSION ${BUILD})
    - NODE=$(getenv.sh NODE_VERSION ${BUILD})
    - NODE_SHORT="${NODE:0:1}"
    - TAGS=( "${NODE}-slim" "${NODE}-${YARN}-slim" "${NODE_SHORT}-slim" "${NODE_SHORT}-${YARN}-slim" "stable-slim" )
    - docker login -u $HUB_USER -p $HUB_PW
    - for tag in "${TAGS[@]}" do \
        docker tag $BUILD ${IMG_NAME}:${tag} \
        docker push ${IMG_NAME}:${TAG} \
      done
  only:
    - master