include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/container_scan-v2.yml

stages:
  - download
  - build
  - scan

variables:
  IMAGE_NAME: jitesoft/node-yarn

download:
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  stage: download
  variables:
    GIT_STRATEGY: none
  before_script:
    - apk add --no-cache gnupg
    - wget -qO- https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --import
  script:
    - wget -q https://yarnpkg.com/latest.tar.gz
    - wget -q https://yarnpkg.com/latest.tar.gz.asc
    - gpg --verify latest.tar.gz.asc
  artifacts:
    when: on_success
    name: yarn
    paths:
      - ./latest.tar.gz
    expire_in: 2 days

.build: &build
  image: registry.gitlab.com/jitesoft/dockerfiles/docker:latest
  stage: build
  dependencies:
    - download
  script:
    - docker build --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-${VERSION} --build-arg "NODE_VERSION=${VERSION}" -f slim/Dockerfile .
    - TAGS="${VERSION} ${EXTRA_TAGS}"
    - |
      for tag in ${TAGS}; do
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-${VERSION} ${CI_REGISTRY_IMAGE}:${tag}-slim
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-${VERSION} ${IMAGE_NAME}:${tag}-slim
        docker push ${CI_REGISTRY_IMAGE}:${tag}-slim
        docker push ${IMAGE_NAME}:${tag}-slim
      done
    - docker build --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-${VERSION} --build-arg "NODE_VERSION=${VERSION}" -f full/Dockerfile .
    - |
      for tag in ${TAGS}; do
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-${VERSION} ${CI_REGISTRY_IMAGE}:${tag}
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}-${VERSION} ${IMAGE_NAME}:${tag}
        docker push ${CI_REGISTRY_IMAGE}:${tag}
        docker push ${IMAGE_NAME}:${tag}
      done

build:stable:
  <<: *build
  variables:
    VERSION: "10"
    EXTRA_TAGS: "stable current lts dubnium"

build:latest:
  <<: *build
  variables:
    VERSION: "12"
    EXTRA_TAGS: "latest"

scan:stable:
  needs:
    - build:stable
  extends: .container_scanning
  variables:
    GIT_STRATEGY: none
    SCANNING_IMAGE_NAME: ${CI_REGISTRY_IMAGE}:stable

scan:latest:
  needs:
    - build:latest
  extends: .container_scanning
  variables:
    GIT_STRATEGY: none
    SCANNING_IMAGE_NAME: ${CI_REGISTRY_IMAGE}:latest
