include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/container_scan-v2.yml

stages:
  - download
  - build
  - scan

variables:
  IMAGE_NAME: jitesoft/node-yarn

download:
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  stage: download
  variables:
    GIT_STRATEGY: none
  before_script:
    - apk add --no-cache gnupg
    - wget -qO- https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --import
  script:
    - wget -q https://yarnpkg.com/latest.tar.gz
    - wget -q https://yarnpkg.com/latest.tar.gz.asc
    - gpg --verify latest.tar.gz.asc
  artifacts:
    when: on_success
    name: yarn
    paths:
      - ./latest.tar.gz
    expire_in: 2 days

.build: &build
  image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
  stage: build
  dependencies:
    - download
  script:
    - TAGS=$(helper "${CI_REGISTRY_IMAGE},jitesoft/node-yarn" "${VERSION}-slim,${EXTRA_TAGS_SLIM}")
    - docker buildx build --platform linux/arm64,linux/amd64 --progress plain --push ${TAGS} --build-arg "NODE_VERSION=${VERSION}" -f slim/Dockerfile .
    - TAGS=$(helper "${CI_REGISTRY_IMAGE},jitesoft/node-yarn" "${VERSION},${EXTRA_TAGS}")
    - docker buildx build --platform linux/arm64,linux/amd64 --progress plain --push ${TAGS} --build-arg "NODE_VERSION=${VERSION}" -f full/Dockerfile .


build:stable:
  <<: *build
  variables:
    VERSION: "12"
    EXTRA_TAGS: "stable,lts,erbium"
    EXTRA_TAGS_SLIM: "stable-slim,lts-slim,erbium-slim"

build:latest:
  <<: *build
  variables:
    VERSION: "13"
    EXTRA_TAGS: "latest"
    EXTRA_TAGS_SLIM: "latest-slim"

scan:stable:
  needs:
    - build:stable
  extends: .container_scanning
  variables:
    GIT_STRATEGY: none
    SCANNING_IMAGE_NAME: ${CI_REGISTRY_IMAGE}:stable

scan:latest:
  needs:
    - build:latest
  extends: .container_scanning
  variables:
    GIT_STRATEGY: none
    SCANNING_IMAGE_NAME: ${CI_REGISTRY_IMAGE}:latest
